frr version 9.1
frr defaults traditional
hostname pe2
log stdout
no ipv6 forwarding
!
interface lo
 ip address 10.255.0.4/32
!
interface eth1
 description link-to-p1
 ip address 10.0.0.5/31
!
interface eth2
 description link-to-p2
 ip address 10.0.0.7/31
!
interface eth3
 description link-to-client-b
 ip address 198.51.100.1/24
!
ip prefix-list CLIENT-B seq 5 permit 198.51.100.0/24
!
route-map RM-CLIENT permit 10
 match ip address prefix-list CLIENT-B
!
router ospf
 ospf router-id 10.255.0.4
 network 10.255.0.4/32 area 0
 network 10.0.0.4/31 area 0
 network 10.0.0.6/31 area 0
 passive-interface lo
!
router bgp 65000
 bgp router-id 10.255.0.4
 no bgp ebgp-requires-policy
 neighbor PROVIDER peer-group
 neighbor PROVIDER remote-as 65000
 neighbor PROVIDER update-source lo
 neighbor PROVIDER next-hop-self
 neighbor 10.255.0.1 peer-group PROVIDER
 neighbor 10.255.0.2 peer-group PROVIDER
 neighbor 10.255.0.3 peer-group PROVIDER
 !
 address-family ipv4 unicast
  redistribute connected route-map RM-CLIENT
  neighbor 10.255.0.1 activate
  neighbor 10.255.0.2 activate
  neighbor 10.255.0.3 activate
 exit-address-family
!
line vty
!
