frr version 9.1
frr defaults traditional
hostname p1
log stdout
no ipv6 forwarding
!
interface lo
 ip address 10.255.0.2/32
!
interface eth1
 description link-to-pe1
 ip address 10.0.0.1/31
!
interface eth2
 description link-to-pe2
 ip address 10.0.0.4/31
!
router ospf
 ospf router-id 10.255.0.2
 network 10.255.0.2/32 area 0
 network 10.0.0.0/31 area 0
 network 10.0.0.4/31 area 0
 passive-interface lo
!
router bgp 65000
 bgp router-id 10.255.0.2
 no bgp ebgp-requires-policy
 neighbor PROVIDER peer-group
 neighbor PROVIDER remote-as 65000
 neighbor PROVIDER update-source lo
 neighbor PROVIDER next-hop-self
 neighbor 10.255.0.1 peer-group PROVIDER
 neighbor 10.255.0.3 peer-group PROVIDER
 neighbor 10.255.0.4 peer-group PROVIDER
 !
 address-family ipv4 unicast
  neighbor 10.255.0.1 activate
  neighbor 10.255.0.3 activate
  neighbor 10.255.0.4 activate
 exit-address-family
!
line vty
!
