---
router_id: 10.255.0.3
loopback_address: 10.255.0.3/32

interfaces:
  - name: eth1
    description: link-to-pe1
    address: 10.0.0.3/31
    ospf: true
  - name: eth2
    description: link-to-pe2
    address: 10.0.0.6/31
    ospf: true

client_subnet: ""

bgp_neighbors:
  - 10.255.0.1
  - 10.255.0.2
  - 10.255.0.4
