---
router_id: 10.255.0.1
loopback_address: 10.255.0.1/32

interfaces:
  - name: eth1
    description: link-to-p1
    address: 10.0.0.0/31
    ospf: true
  - name: eth2
    description: link-to-p2
    address: 10.0.0.2/31
    ospf: true
  - name: eth3
    description: link-to-client-a
    address: 192.0.2.1/24
    ospf: false

client_subnet: 192.0.2.0/24

bgp_neighbors:
  - 10.255.0.2
  - 10.255.0.3
  - 10.255.0.4
